# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dd25aba3d58b011bdbae0bf0881719ae7172e22909601603895cf14fc491b51b7c46ad9a6d292c962d62689ca9feae74ce9a17afdb4c55d9ea7b56a58a46b06

test:
  secret_key_base: ef6e44f98a5db8abb9f24854bd495b0c760245be22bcfbbff4df385fbe12ca18cae7c2454dcd2d1bb2496b7fe2a39831fb571c1234f0e689cb8a0f13bed89594

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
